name: tflint

on: [push]

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout source code
    - uses: terraform-linters/setup-tflint@v6
      name: Setup TFLint
      with:
        tflint_version: v0.52.0
        cache: true